runtime: python37
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

entrypoint: python bot.py

env_variables:
  PROJECT_ID: "885964706899"

handlers:
- url: /
  static_dir: static_html
